### ISSUE TITLE
Roadmap to v0.1

### ISSUE THREAD

**Issue by tyvsmith** [tyvsmith/android-studio-webtop#2]
- [ ] Move files in dockerfile to be checked in
- [ ] Nest Virtualization on all CPUs
- [ ] Pre setup Andorid SDK, run SDK manager on latest, and configure AS XML files to point to it
- [ ] Skip first launch telemetry prompt
- [ ] Supported user provided repo URL that will clone and open in AS
- [ ] Setup CI, CoC, basic contribution requirements.
